JMS:
    BROKER:
        URL: t3://localhost:7001
    ERROR:
        QUEUE:
            NAME: com.chandra.weblogic.base.eq
    JMS_FACTORY: com.chandra.weblogic.base.cf
    JNDI_FACTORY: weblogic.jndi.WLInitialContextFactory
    LOGGING:
        QUEUE:
            NAME: com.chandra.weblogic.base.lq
    NOTIFICATION:
        QUEUE:
            NAME: com.chandra.weblogic.base.nq
    TRACKING:
        QUEUE:
            NAME: com.chandra.weblogic.base.tq
afpo:
    logging:
        web: 'yes'
    notification: 'yes'
    notification.url: http://localhost:9082/afpo/events/notifications
    test:
        prop: testchanged10
context:
    path: com.oracle.xmlns.eventdetails
mail:
    debug: false
    smtp:
        auth: false
        starttls:
            enable: false
    transport:
        protocol: smtp
management:
    security:
        enabled: false
notify:
    attachment:
        filename: AfpoNotification.txt
        type: text/plain; charset=UTF-8
    body: |-
        Dear Sir/Madam,

        Find your message details attached.

        Regards,
        AFPO
    from:
        email: no-reply@globalinsurance.com
    subject: Notification
    to:
        email: c.lakshminarayanan@accenture.com
schema:
    location: xsd/EventDetails.xsd
server:
    port: 9081
spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1
            connection-timeout: 60000
            driver-class-name: com.mysql.jdbc.Driver
            jdbc-url: jdbc:mysql://localhost:3306/afpo_soa?useSSL=false
            maximum-pool-size: 100
            password: root
            pool-name: afpoLoggingCP
            username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
    mail:
        host: soa-host1
        port: 25
