---
server:
  port: 9081
---
  context:
    path: com.oracle.xmlns.eventdetails
  schema:
    location: xsd/EventDetails.xsd
  spring: 
    mail: 
      host: soa-host1
      port: 25
  notify:
    to:
      email: c.lakshminarayanan@accenture.com
    from:
      email: no-reply@globalinsurance.com
    subject: Notification
    body: Dear Sir/Madam,\n\nFind your message details attached.\n\nRegards,\nAFPO
    attachment:
      filename: AfpoNotification.txt
      type: text/plain; charset=UTF-8
  mail:
    transport: 
      protocol: smtp
    smtp:
      auth: false
      starttls:
        enable: false
    debug: false
  management: 
    security: 
      enabled: false
  afpo:
    notification:
      url: http://localhost:9082/afpo/events/notifications
    logging: 
      web: yes
    notification: yes
    test:
      prop: testchanged10      
  JMS:
    JNDI_FACTORY: weblogic.jndi.WLInitialContextFactory
    JMS_FACTORY: com.chandra.weblogic.base.cf
    BROKER:
      URL: t3://localhost:7001
    LOGGING:
      QUEUE:
        NAME: com.chandra.weblogic.base.lq
    ERROR:
      QUEUE:
        NAME: com.chandra.weblogic.base.eq
    TRACKING: 
        QUEUE:
          NAME: com.chandra.weblogic.base.tq
    NOTIFICATION: 
        QUEUE:
          NAME: com.chandra.weblogic.base.nq
---
  spring:
    profiles: oracle, default
    datasource:
      hikari:
        jdbc-url: jdbc:oracle:thin:@localhost:1521/xe
        username: afpo_soa
        password: oracle
        driver-class-name: oracle.jdbc.driver.OracleDriver
        connection-test-query: SELECT 1 from dual
        pool-name: afpoLoggingCP
    jpa: 
      properties: 
        hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      hibernate.ddl-auto: update
---
  spring:
    profiles: mysql, default
  datasource:
      hikari:
        jdbc-url: jdbc:mysql://localhost:3306/afpo_soa?useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        connection-test-query: SELECT 1
        pool-name: afpoLoggingCP
      jpa: 
        properties: 
          hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
        show-sql: true
        hibernate.ddl-auto: update


